version: '3'

networks:
  frontend:
  backend:

services:
  php-fpm:
    container_name: php_fpm
    build: .devops/php-fpm
    volumes:
      - .:/var/www/app
    networks:
      - backend
    links:
      - mysql
    ports:
      - "9000:9000"

  nginx:
    container_name: nginx
    build: .devops/nginx
    volumes:
      - .:/var/www/app
    networks:
      - frontend
      - backend
    ports:
      - "1234:80"
    links:
      - php-fpm

  mysql:
    env_file:
      - .env
    container_name: mysql
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    ports:
      - "${DB_PORT}:3306"
    networks:
      - backend
